_select_data:
  aspect-ratios:
    one-third: одна треть
    one-half: одна вторая
    two-thirds: две трети
    full-width: во всю длину

  column-sizes:
    col-one-third: Одна Треть
    col-one-half: Одна Вторая
    col-two-thirds: Две Трети
    col-full-width: Во всю длину