seo:
  site_name: Стилист Мария Евдокимова
  title: Стилист и трендвотчер Мария Евдокимоваа
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  footer_color: '#e6e0d0'